### ISSUE TITLE
'builtin_function_or_method object' has no attribute 'matched'"} issue

### ISSUE THREAD

**Issue by mklatsky** [haos616/ansible-haproxy-letsencrypt#3]
When I use this role, the following error occurs:

`FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'builtin_function_or_method object' has no attribute 'matched'"}`

**VERSIONS**:
Ansible version 2.3.1

**Expected behavior:**
Using the ansible role allows letsencrypt to be installed and configured, with an appropriate harproxy.cfg file. Specifically, if a certificate exists in the defined haproxy_certs_dir, then the https frontend stanza is populated.

This appears to be the offending line (in templates/haproxy.cfg.j2):
`{% if haproxy_certs_dir_find.matched > 0 %}`

Please let me know if you need any more information.

**Comment by haos616** [comment]
Hi @mklatsky this role need using with haos616/ansible-haproxy

**Comment by haos616** [comment]
Example:
group_vars/all.yml
```
haproxy_config_template: "{{ playbook_dir }}/roles/letsencrypt/templates/haproxy.cfg.j2"

letsencrypt_admin_email: 'haos616@gmail.com'
letsencrypt_version: '0.15.0'
```

services-deploy.yml
```
---
- hosts: all
  strategy: free
  become_user: root
  become: yes
  gather_facts: yes
  tags: ['deploy', 'setup']
  roles:
    - { role: letsencrypt, task: init }
    - { role: haproxy, task: deploy }
    - { role: letsencrypt, task: create }
    - { role: haproxy, task: deploy, fake: 1 }

```

services-setup.yml
```
---
- hosts: all
  strategy: free
  become_user: root
  become: yes
  gather_facts: yes
  tags: ['setup']
  roles:
    - { role: letsencrypt, task: init }
    - { role: haproxy, task: setup }
    - { role: haproxy, task: dirs }
    - { role: docker, task: setup }
    - { role: letsencrypt, task: setup }
    - { role: letsencrypt, task: renew }

```
